"""PROTOTYPE: emit a Kick Assembler source for the defMON image and
round-trip it byte-exact, using Kick Assembler's native illegal-opcode
mnemonics (so the $2B/$EB duplicate encodings 64tass renders as `.byte`
become real `anc2`/`sbc2` instructions).

This is a feasibility prototype, not the production emitter: operands are
rendered as raw hex (no label resolution / annotations / .block scoping).
It exists to answer "can Kick Assembler reproduce the image byte-for-byte,
including the illegals?" — which it does. A full labelled KickAss dialect
would build on emit_defmon_source.py's label layers.

    python3 -m tools.re.emit_kickass --out build/defmon_kickass.asm
"""

from __future__ import annotations
import argparse
from pathlib import Path

from tools.re.dasm6502 import OPS
from tools.re.emit_defmon_source import (
    END_ADDR_EXCL,
    LOAD_ADDR,
    SEED_LANDMARKS,
    classify,
    expand_code_starts,
    load_code_starts,
)

REPO = Path(__file__).resolve().parents[2]
STATIC_BIN = REPO / "artefacts" / "defmon-static.bin"
ENTRYPOINTS = REPO / "trace" / "entrypoints.json"

# KickAss mnemonics for the illegals: most match the OPS table (lowercased),
# but the duplicate encodings get their KickAss-specific aliases.
_KA_MNEMONIC_BY_OPCODE = {0x2B: "anc2", 0xEB: "sbc2"}


def _operand(mode: str, p1: int, p2: int, pc: int, opcode: int) -> str:
    if mode == "imp" or mode == "acc":
        return ""
    if mode == "imm":
        return f"#${p1:02x}"
    if mode == "zp":
        return f"${p1:02x}"
    if mode == "zpx":
        return f"${p1:02x},x"
    if mode == "zpy":
        return f"${p1:02x},y"
    if mode == "izx":
        return f"(${p1:02x},x)"
    if mode == "izy":
        return f"(${p1:02x}),y"
    addr = p1 | (p2 << 8)
    # KickAss auto-sizes; force absolute when an abs-mode operand fits in a
    # byte so it doesn't shrink to zero-page and break the round-trip.
    force = ".a" if addr < 0x100 else ""
    if mode == "abs":
        return f"${addr:04x}"
    if mode == "abx":
        return f"${addr:04x},x"
    if mode == "aby":
        return f"${addr:04x},y"
    if mode == "ind":
        return f"(${addr:04x})"
    if mode == "rel":
        off = p1 - 256 if p1 >= 0x80 else p1
        return f"${(pc + 2 + off) & 0xFFFF:04x}"
    return "???"


def emit(mem: bytes, instr_at: dict, start: int, end: int) -> str:
    lines = [
        f"// generated by emit_kickass.py (prototype)",
        f".cpu _6502",
        f"*=${start:04x}",
    ]
    pc = start
    data_run: list[int] = []

    def flush_data():
        nonlocal data_run
        for i in range(0, len(data_run), 16):
            chunk = data_run[i : i + 16]
            lines.append("    .byte " + ", ".join(f"${b:02x}" for b in chunk))
        data_run = []

    while pc < end:
        info = instr_at.get(pc)
        if info is None:
            data_run.append(mem[pc])
            pc += 1
            continue
        flush_data()
        mnem, mode, n = info
        opcode = mem[pc]
        # zp-range abs operand needs an explicit absolute force in KickAss
        p1 = mem[pc + 1] if n >= 2 else 0
        p2 = mem[pc + 2] if n >= 3 else 0
        ka_mnem = _KA_MNEMONIC_BY_OPCODE.get(opcode, mnem.lower())
        op = _operand(mode, p1, p2, pc, opcode)
        force = ""
        if mode in ("abs", "abx", "aby") and (p1 | (p2 << 8)) < 0x100:
            force = ".a"
        lines.append(f"    {ka_mnem}{force} {op}".rstrip())
        pc += n
    flush_data()
    return "\n".join(lines) + "\n"


def main(argv=None):
    import subprocess

    ap = argparse.ArgumentParser()
    ap.add_argument("--bin", default=str(STATIC_BIN))
    ap.add_argument("--out", default=str(REPO / "build" / "defmon_kickass.asm"))
    ap.add_argument("--jar", default="/usr/local/kickass/KickAss.jar")
    ap.add_argument(
        "--roundtrip",
        action="store_true",
        help="assemble with Kick Assembler and verify byte-exact",
    )
    args = ap.parse_args(argv)
    mem = Path(args.bin).read_bytes()
    seeds = load_code_starts(ENTRYPOINTS)
    seeds.update(SEED_LANDMARKS.keys())
    expanded = expand_code_starts(mem, seeds, LOAD_ADDR, END_ADDR_EXCL)
    instr_at, _ = classify(mem, expanded, LOAD_ADDR, END_ADDR_EXCL)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(emit(mem, instr_at, LOAD_ADDR, END_ADDR_EXCL))
    print(f"emit_kickass: wrote {out}")
    if not args.roundtrip:
        return 0
    prg = out.with_suffix(".prg")
    subprocess.run(
        ["java", "-jar", args.jar, str(out), "-o", str(prg)],
        check=True,
        capture_output=True,
    )
    body = prg.read_bytes()[2:]  # strip 2-byte PRG load address
    ref = mem[LOAD_ADDR : LOAD_ADDR + len(body)]
    if body == ref:
        print(
            f"roundtrip-kickass: PASS — {len(body)}-byte match "
            f"(${LOAD_ADDR:04X}-${LOAD_ADDR + len(body):04X})"
        )
        return 0
    bad = next(i for i in range(len(body)) if body[i] != ref[i])
    print(f"roundtrip-kickass: FAIL at ${LOAD_ADDR + bad:04X}")
    return 1


if __name__ == "__main__":
    import sys

    sys.exit(main())
